### ISSUE TITLE
My add-on with fire-fox has stopped working, i removed, and re-installed, still not working, any ideas?

### ISSUE THREAD

**Issue by StephenEvans51** [MicroDroid/youtube-download-button#12]
My add-on with fire-fox has stopped working, i removed, and re-installed, still not working, any ideas?  I upgraded firefox and reinstalled again, still nothing...  even on files I have been able to download before.

**Comment by StephenEvans51** [comment]
Am I the only one having this problem?  If so, then it would be helpful to know this.  I like this add-on, but if I need to give up an try another, i guess i will, but i'll wait a bit in case there is some bug that can be fixed...

**Comment by MicroDroid** [comment]
This has been fixed, please update the extension to the latest version and try again.

**Comment by StephenEvans51** [comment]
Thank you so much, yes, it is working again!!! :D

**Comment by StephenEvans51** [comment]
WTF?  I already gave you a 5 star review long ago...  don't you see it? :(

you want me to delete it and add it again?  it won't let me add a review
when I' already added one...

**Comment by MicroDroid** [comment]
I was being sarcastic 😜

**Comment by StephenEvans51** [comment]
Thanks again for the fix.  FYI, on the support page, it says "
Contributions are welcome "...  How does one make a contribution?  I gave
you a 5 star review long ago, but wouldn't mind giving a few dollars as
well, to show appreciation.

**Comment by MicroDroid** [comment]
Contributions could be anything, helping to develop the extension by writing code, donating money to developers, etc.

If you happen to have some bitcoins around, you can send your donations here `16dt5DdjGvduZ3KZcFrwsBA82qqfrcbeUQ`, and if not thanks anyways.

**Comment by StephenEvans51** [comment]
Sorry, I have no bitcoins...
