### ISSUE TITLE
How to edit extension? What do the python and css do?

### ISSUE THREAD

**Issue by Epikest** [MicroDroid/youtube-download-button#2]

**Comment by MicroDroid** [comment]
Hi @Epikest 

The extension is made using JavaScript, as with all browser extensions, and not Python.

To use the extension, if you're a Firefox user, you can find it in the store. If you're, however, a Chrome user, then you need to do the following:

- Clone the repository
- `npm i && npm run build`
- Then, in your Chrome browser, enable Development Mode in the extensions page
- Drag the `build/` folder into the extensions page.

If you experience any issue with the steps above, let me know.
