### ISSUE TITLE
Button do not work

### ISSUE THREAD

**Issue by Matrixxx3** [MicroDroid/youtube-download-button#3]
Button do not work, and this is a very good extension, so I are using some time to show you the problem.

* When clicking the button the "loading" is showing for a couple of seconds (picture 1)
* Then "loading" disappear and a faint gray background stripe is remaining. (picture 2). Nothing more is happening.
* If I click the button again, the "gray background stipe" disappears
* If I click the button once more "gray background stipe" is showing again
* I have dissable every extensions except yours, but the same problem. (picture 3)
This worked until I think one day in August (?), and then suddenly didn't work anymore. Could it have been because of a FF upgrade?  

Please try to fix this!

Thank you! :-)

(FF 69.0 | Win 10 proff)
![Skjermbilde (486)_LI](https://user-images.githubusercontent.com/55065176/64494814-b1683c00-d291-11e9-8035-f23606d934c9.jpg)
![Skjermbilde (487)_LI](https://user-images.githubusercontent.com/55065176/64494813-b1683c00-d291-11e9-9682-3879c022b824.jpg)
![Skjermbilde (488)_LI](https://user-images.githubusercontent.com/55065176/64494812-b1683c00-d291-11e9-9511-851252697c8b.jpg)

**Comment by MicroDroid** [comment]
I pushed a possible fix, I'll test this and if it works, I'll push the update on Firefox Store

**Comment by MicroDroid** [comment]
Bug fixed and a new version has been pushed. Few moments until Firefox Add-ons reviewers take a look at the new version and then it'll be up.

Thanks for your detailed report. :)

**Comment by Matrixxx3** [comment]
Thank you so much, It works again! :-)
Bravo, and so fast fix!!!
