### ISSUE TITLE
undefined links

### ISSUE THREAD

**Issue by AlB80** [MicroDroid/youtube-download-button#7]
On some videos or channels plugin shows normal list, but all links are broken: https://www.youtube.com/undefined

f.e. B0CuLzsivzA and all videos from this channel

**Comment by MicroDroid** [comment]
There is a bug in the library itself [here](https://github.com/fent/node-ytdl-core/issues/632).

I'll keep track of it and when it's fixed, I'll push an update to this extension.

**Comment by MicroDroid** [comment]
Someone please scream so I fix this

**Comment by AlB80** [comment]
Are you finished with this issue yet?

**Comment by MicroDroid** [comment]
Hi @AlB80,

It took a little while for your scream to cross the galaxy to reach this planet where I am. Anyways new version is now up!
